In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score
from sklearn.metrics import classification_report, confusion_matrix
import matplotlib.pyplot as plt
%matplotlib inline
from sklearn.model_selection import RandomizedSearchCV
from sklearn.utils import shuffle

In [2]:
names = ['UserId', 'Nationality', 'Occupation', 
         'TransDate', 'Sector', 'Sender Currency', 'Sender Amount', 'PaymentMethod', 'Sourceof Fund',
         'Source of Fund Others', 'Purpose', 'TransactionStatus', 'Pickup Country', 'Relationship',
        'Pickup Type','IssuerCode','RiskScore','Risk Ranking','WeekFrequency','MonthFrequency' ,'YearFrequency', 'Freq2017', 'Freq2018', 'Freq2019']

df = pd.read_csv('dbtikfx_my_new.csv', names = names)

C:\Users\joey.lim\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3063: DtypeWarning: Columns (9) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [3]:
# Meaning of terms :
# blue collar-Skilled workers who do labor using their hands, or so-called manual and technical labor.
# white_collar-Typically associated with a desk job, these people are usually tasked with clerical, administrative, and 
#              managerial functions. 
# no_collar-Cannot be categorized into any collar characteristics
blue_collar=['AGRICULTURAL_FORESTRY_FARMING_AND_FISHERY_WORKERS_NOT_ELSEWHERE_CLASSIFIED','MANUFACTURING_LABOURERS_NOT_ELSEWHERE_CLASSIFIED',
            'SECURITY_GUARDS','HAND_OR_PEDAL_VEHICLE_DRIVERS','KITCHEN_HELPERS','DOMESTIC_HOUSEKEEPERS', 'CHEFS',
            'BUILDING_CONSTRUCTION_LABOURERS','BARTENDERS','STALL_AND_MARKET_SALESPERSONS','CAR_TAXI_AND_VAN_DRIVERS',
            'MOTORCYCLE_RIDERS_(DRIVERS)','CIVIL_ENGINEERING_LABOURERS','FOOD_COUNTER_ATTENDANTS','CROP_FARM_LABOURERS',
            'SHOP_SUPERVISORS','CONSTRUCTION_SUPERVISORS', 'HEAVY_TRUCK_AND_LORRY_DRIVERS','MOTOR_VEHICLE_TECHNICIANS',
            'CHEMICAL_PRODUCTS_PLANT_AND_MACHINE_OPERATORS','TRAVEL_GUIDES_or_AGENTS','DOMESTIC_CLEANERS_AND_HELPERS',
            'CLEANERS_AND_HELPERS_IN_OFFICES_HOTEL_AND_OTHER_ESTABLISHMENTS','COOKS','SALES_WORKERS_NOT_ELSEWHERE_CLASSIFIED',
            'TRANSPORT_CONDUCTORS','CHILD_CARE_WORKERS','SALES_DEMONSTRATORS','SHOP_SALES_ASSISTANTS','GENERAL_DUTY_OFFICERS_(MA)',
            'BUSINESS_SERVICES_MANAGERS','FIELD_CROP_GROWERS','SHOPKEEPERS','ELECTRONICS_ENGINEERING_TECHNICIANS']

white_collar=['OTHER_SUPERVISORS_NOT_ELSEWHERE_CLASSIFIED','CLERICAL_SUPPORT_WORKERS_NOT_ELSEWHERE_CLASSIFIED','MANUFACTURING_MANAGERS',
             'EMPLOYMENT_AGENTS_AND_CONTRACTORS','MANAGING_DIRECTORS_AND_CHIEF_EXECUTIVES_OTHERS','MANAGING_DIRECTORS_AND_CHIEF_EXECUTIVES_SERVICES',
             'OTHER_SERVICES_MANAGERS_NOT_ELSEWHERE_CLASSIFIED','SECONDARY_EDUCATION_TEACHERS','MANUFACTURING_SUPERVISORS',
             'ADMINISTRATIVE_AND_EXECUTIVE_SECRETARIES','UNIVERSITY_AND_HIGHER_EDUCATION_TEACHING_PROFESSIONAL','BANK_TELLERS_AND_RELATED_CLERKS',
             "TEACHERâ€™S_AIDES", 'PRODUCTION_CLERKS','MEDICAL_ASSISTANTS','MANAGING_DIRECTORS_AND_CHIEF_EXECUTIVES_MANUFACTURING',
             'MANAGING_DIRECTORS_AND_CHIEF_EXECUTIVES_AGRICULTURE','CONSTRUCTION_MANAGERS','MANAGING_DIRECTORS_AND_CHIEF_EXECUTIVES_CONSTRUCTION',
             'CLIENT_INFORMATION_WORKERS_NOT_ELSEWHERE_CLASSIFIED','RETAIL_AND_WHOLESALE_TRADE_MANAGERS','TEACHING_PROFESSIONALS_NOT_ELSEWHERE_CLASSIFIED',
             'DATA_ENTRY_CLERKS','CASHIERS_AND_TICKET_CLERKS','ADMINISTRATIVE_MANAGERS','CUSTOMER_SERVICE_or_CONTACT_or_CALL_CENTRE_INFORMATION_CLERKS',
             'ADMINISTRATIVE_PROFESSIONALS','MINING_SUPERVISORS','RELIGIOUS_TEACHERS','FINANCIAL_ANALYSTS','ARTS_TEACHERS','FINANCE_MANAGERS_SERVICES',
             'SALES_AND_MARKETING_MANAGERS','INFORMATION_AND_COMMUNICATIONS_TECHNOLOGY_MANAGERS','FINANCE_MANAGERS_OTHERS',
             'ACCOUNTING_ASSOCIATE_PROFESSIONALS','ADVERTISING_AND_MARKETING_PROFESSIONALS','Accountants',
              'ENGINEERING_PROFESSIONALS_NOT_ELSEWHERE_CLASSIFIED','TRAINING_AND_STAFF_DEVELOPMENT_PROFESSIONALS','INDUSTRIAL_AND_PRODUCTION_ENGINEERS',
            'GENERALIST_MEDICAL_PRACTITIONERS','SYSTEMS_ANALYSTS','LEGAL_PROFESSIONALS_NOT_ELSEWHERE_CLASSIFIED','SHIP_ENGINEERS',
             'MECHANICAL_ENGINEERS','FINANCIAL_AND_INVESTMENT_ADVISERS','CODING_PROOF_READING_AND_RELATED_CLERKS']

no_collar=['HouseWife','Unemployed','TOURISTS','UNKNOWN','RETIREE','DESPATCH_or_RUNNER','STUDENT']

df["Collar_Type"]="NaN"
# Categorize the occupations into its collar type
for i in range(len(df)) :
    if df["Occupation"][i] in blue_collar:
        df["Collar_Type"][i]="blue"
        
    elif df["Occupation"][i] in white_collar:
        df["Collar_Type"][i]="white"
        
    elif df["Occupation"][i] in no_collar:
        df["Collar_Type"][i]="no_collar"

C:\Users\joey.lim\Anaconda3\lib\site-packages\ipykernel_launcher.py:37: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\joey.lim\Anaconda3\lib\site-packages\ipykernel_launcher.py:43: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\joey.lim\Anaconda3\lib\site-packages\ipykernel_launcher.py:40: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [4]:
df["PaymentMethod"].unique()

array(['CASH', 'DEBITCARD', 'NONE', 'ONLINE', 'ONLINE.DEBITCARD',
       'VIRTUALACCOUNT'], dtype=object)

In [25]:
df.isnull().sum()

UserId                       0
Nationality                  0
Occupation                   0
TransDate                    0
Sector                    5825
Sender Currency              0
Sender Amount                0
PaymentMethod                0
Sourceof Fund                0
Source of Fund Others    71225
Purpose                      0
TransactionStatus            0
Pickup Country               0
Relationship                 0
Pickup Type                  0
IssuerCode                   0
RiskScore                    0
Risk Ranking                 0
WeekFrequency            71232
MonthFrequency           71232
YearFrequency            71232
Freq2017                 71232
Freq2018                 71232
Freq2019                 71232
Collar_Type                  0
dtype: int64

In [26]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 71232 entries, 0 to 71231
Data columns (total 25 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   UserId                 71232 non-null  int64
 1   Nationality            71232 non-null  object
 2   Occupation             71232 non-null  object
 3   TransDate              71232 non-null  object
 4   Sector                 65407 non-null  object
 5   Sender Currency        71232 non-null  object
 6   Sender Amount          71232 non-null  float64
 7   PaymentMethod          71232 non-null  object
 8   Sourceof Fund          71232 non-null  object
 9   Source of Fund Others  7 non-null      object
 10  Purpose                71232 non-null  object
 11  TransactionStatus      71232 non-null  object
 12  Pickup Country         71232 non-null  object
 13  Relationship           71232 non-null  object
 14  Pickup Type            71232 non-null  object
 15  IssuerCode             71232 non-null  object
 16  RiskScore              71232 non-null  int64
 17  Risk Ranking           71232 non-null  object
 18  WeekFrequency          0 non-null      float64
 19  MonthFrequency         0 non-null      float64
 20  YearFrequency          0 non-null      float64
 21  Freq2017               0 non-null      float64
 22  Freq2018               0 non-null      float64
 23  Freq2019               0 non-null      float64
 24  Collar_Type            71232 non-null  object
dtypes: float64(7), int64(2), object(16)
memory usage: 13.6+ MB

In [27]:
df.Sector.fillna('Others', inplace = True)
df['Freq2017'].fillna(value = 0, inplace = True)
df['Freq2018'].fillna(value = 0, inplace = True)
df['Freq2019'].fillna(value = 0, inplace = True)
df['TransDate'] = pd.to_datetime(df['TransDate']).dt.date
df['TransDate'] = pd.to_datetime(df['TransDate'], format = ("%Y-%m-%d"))
df = df.sort_values(by=['UserId', 'TransDate'])
df = df.reset_index(drop = True)

In [28]:

df.head()

,UserId,Nationality,Occupation,TransDate,Sector,Sender Currency,Sender Amount,PaymentMethod,Sourceof Fund,Source of Fund Others,...,IssuerCode,RiskScore,Risk Ranking,WeekFrequency,MonthFrequency,YearFrequency,Freq2017,Freq2018,Freq2019,Collar_Type
0,41,ID,HouseWife,2017-11-18,Others,MYR,500.00,CASH,SAVINGS,NaN,...,123,19,Low,NaN,NaN,NaN,0.0,0.0,0.0,no_collar
1,41,ID,HouseWife,2017-11-20,Others,MYR,500.00,CASH,SALARY,NaN,...,123,19,Low,NaN,NaN,NaN,0.0,0.0,0.0,no_collar
2,51,PH,CLERICAL_SUPPORT_WORKERS_NOT_ELSEWHERE_CLASSIFIED,2017-09-01,Others,MYR,337.93,CASH,SALARY,NaN,...,CPCL,29,Low,NaN,NaN,NaN,0.0,0.0,0.0,white
3,51,PH,CLERICAL_SUPPORT_WORKERS_NOT_ELSEWHERE_CLASSIFIED,2017-09-29,Others,MYR,351.21,CASH,FAMILY_INCOME,NaN,...,CPCL,33,Low,NaN,NaN,NaN,0.0,0.0,0.0,white
4,51,PH,CLERICAL_SUPPORT_WORKERS_NOT_ELSEWHERE_CLASSIFIED,2017-10-31,Others,MYR,329.48,CASH,SALARY,NaN,...,CPCL,32,Low,NaN,NaN,NaN,0.0,0.0,0.0,white

In [29]:

def YearFreq(dff):
    i = 0
    j = 0
    while i != dff.shape[0]:
        yearfreq = 0
        userid = dff['UserId'][i]
        firstday = dff['TransDate'][i]
        yearfreq = yearfreq + 1
        days_in_a_year = 365
        j = j + 1
        
        while (j != dff.shape[0]) and (dff['UserId'][j] == userid):
            if (dff['TransDate'][j] - firstday).days < days_in_a_year:
                yearfreq = yearfreq + 1
            else:
                break
                
            if (j == dff.shape[0]):
                pass
            else:
                j = j + 1
                
        while i != j:
            
            dff['YearFrequency'][i] = yearfreq
            i = i + 1

In [30]:
def MonthFreq(dff):
    i = 0
    j = 0
    while i != dff.shape[0]:
        monthfreq = 0
        userid = dff['UserId'][i]
        firstday = dff['TransDate'][i]
        monthfreq = monthfreq + 1
        days_in_a_month = 30
        j = j + 1
        
        while (j != dff.shape[0]) and (dff['UserId'][j] == userid):
            if (dff['TransDate'][j] - firstday).days < days_in_a_month:
                monthfreq = monthfreq + 1
            else:
                break
                
            if (j == dff.shape[0]):
                pass
            else:
                j = j + 1
                
        while i != j:
            
            dff['MonthFrequency'][i] = monthfreq
            i = i + 1

In [31]:
def WeekFreq(dff):
    i = 0
    j = 0
    while i != dff.shape[0]:
        weekfreq = 0
        userid = dff['UserId'][i]
        firstday = dff['TransDate'][i]
        weekfreq = weekfreq + 1
        days_in_a_week = 7
        j = j + 1
        
        while (j != dff.shape[0]) and (dff['UserId'][j] == userid):
            if (dff['TransDate'][j] - firstday).days < days_in_a_week:
                weekfreq = weekfreq + 1
            else:
                break
                
            if (j == dff.shape[0]):
                pass
            else:
                j = j + 1
                
        while i != j:
            
            dff['WeekFrequency'][i] = weekfreq
            i = i + 1

In [32]:
def FreqEachYear(dff):
    i = 0
    j = 0
    
    
    while i != dff.shape[0] :
        Freq2017 = 0
        Freq2018 = 0
        Freq2019 = 0
        userid = dff['UserId'][i]
        
        while (j != dff.shape[0]) and (dff['UserId'][j] == userid) :
            if dff['TransDate'][j].year == 2017:
                Freq2017 = Freq2017 + 1
            elif dff['TransDate'][j].year == 2018:
                Freq2018 = Freq2018 + 1
            elif dff['TransDate'][j].year == 2019:
                Freq2019 = Freq2019 + 1
            if (j == dff.shape[0]):
                pass
            else:
                j = j + 1
        #userid = dff['UserId'][j]
        while i != j:
            if (dff['TransDate'][i].year == 2017) and (dff['UserId'][i] == userid) :
                dff['Freq2017'][i] = Freq2017
           
            elif (dff['TransDate'][i].year == 2018) and (dff['UserId'][i] == userid) :
                dff['Freq2018'][i] = Freq2018
            
            elif (dff['TransDate'][i].year == 2019) and (dff['UserId'][i] == userid) :
                dff['Freq2019'][i] = Freq2019
            i = i + 1

In [33]:
YearFreq(df)
MonthFreq(df)
WeekFreq(df)
FreqEachYear(df)

C:\Users\joey.lim\Anaconda3\lib\site-packages\ipykernel_launcher.py:25: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\joey.lim\Anaconda3\lib\site-packages\ipykernel_launcher.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\joey.lim\Anaconda3\lib\site-packages\ipykernel_launcher.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\joey.lim\Anaconda3\lib\site-packages\ipykernel_launcher.py:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [34]:
df[['UserId', 'TransDate', 'MonthFrequency', 'YearFrequency', 'Freq2017', 'Freq2018', 'Freq2019' ]].head(50)

,UserId,TransDate,MonthFrequency,YearFrequency,Freq2017,Freq2018,Freq2019
0,41,2017-11-18,2.0,2.0,2.0,0.0,0.0
1,41,2017-11-20,2.0,2.0,2.0,0.0,0.0
2,51,2017-09-01,2.0,11.0,3.0,0.0,0.0
3,51,2017-09-29,2.0,11.0,3.0,0.0,0.0
4,51,2017-10-31,1.0,11.0,3.0,0.0,0.0
5,51,2018-01-05,2.0,11.0,0.0,13.0,0.0
6,51,2018-01-20,2.0,11.0,0.0,13.0,0.0
7,51,2018-02-19,1.0,11.0,0.0,13.0,0.0
8,51,2018-04-02,1.0,11.0,0.0,13.0,0.0
9,51,2018-05-17,1.0,11.0,0.0,13.0,0.0
10,51,2018-07-01,2.0,11.0,0.0,13.0,0.0
11,51,2018-07-01,2.0,11.0,0.0,13.0,0.0
12,51,2018-08-06,1.0,11.0,0.0,13.0,0.0
13,51,2018-09-05,3.0,11.0,0.0,13.0,0.0
14,51,2018-09-26,3.0,11.0,0.0,13.0,0.0
15,51,2018-10-03,3.0,11.0,0.0,13.0,0.0
16,51,2018-10-26,1.0,11.0,0.0,13.0,0.0
17,51,2018-11-27,1.0,11.0,0.0,13.0,0.0
18,51,2019-01-17,2.0,11.0,0.0,0.0,6.0
19,51,2019-01-28,2.0,11.0,0.0,0.0,6.0
20,51,2019-02-27,4.0,11.0,0.0,0.0,6.0
21,51,2019-03-07,4.0,11.0,0.0,0.0,6.0
22,51,2019-03-18,4.0,11.0,0.0,0.0,6.0
23,51,2019-03-18,4.0,11.0,0.0,0.0,6.0
24,75,2017-12-19,2.0,3.0,1.0,0.0,0.0
25,75,2018-01-10,2.0,3.0,0.0,2.0,0.0
26,75,2018-04-08,1.0,3.0,0.0,2.0,0.0
27,80,2018-12-06,3.0,9.0,0.0,3.0,0.0
28,80,2018-12-06,3.0,9.0,0.0,3.0,0.0
29,80,2018-12-23,3.0,9.0,0.0,3.0,0.0
30,80,2019-01-06,2.0,9.0,0.0,0.0,6.0
31,80,2019-01-06,2.0,9.0,0.0,0.0,6.0
32,80,2019-02-08,4.0,9.0,0.0,0.0,6.0
33,80,2019-02-08,4.0,9.0,0.0,0.0,6.0
34,80,2019-03-04,4.0,9.0,0.0,0.0,6.0
35,80,2019-03-06,4.0,9.0,0.0,0.0,6.0
36,90,2018-02-20,2.0,69.0,0.0,59.0,0.0
37,90,2018-03-11,2.0,69.0,0.0,59.0,0.0
38,90,2018-03-30,7.0,69.0,0.0,59.0,0.0
39,90,2018-04-09,7.0,69.0,0.0,59.0,0.0
40,90,2018-04-15,7.0,69.0,0.0,59.0,0.0
41,90,2018-04-18,7.0,69.0,0.0,59.0,0.0
42,90,2018-04-26,7.0,69.0,0.0,59.0,0.0
43,90,2018-04-28,7.0,69.0,0.0,59.0,0.0
44,90,2018-04-28,7.0,69.0,0.0,59.0,0.0
45,90,2018-05-02,2.0,69.0,0.0,59.0,0.0
46,90,2018-05-04,2.0,69.0,0.0,59.0,0.0
47,90,2018-06-12,3.0,69.0,0.0,59.0,0.0
48,90,2018-07-08,3.0,69.0,0.0,59.0,0.0
49,90,2018-07-11,3.0,69.0,0.0,59.0,0.0

In [35]:
df = shuffle(df)

In [36]:
X = df.drop(['UserId', 'TransDate', 'Source of Fund Others', 'TransactionStatus', 
             'IssuerCode', 'RiskScore'], axis = 1)

In [37]:
x_high=X[X['Risk Ranking']=='High']
x_low=X[X['Risk Ranking']=='Low']
x_medium=X[X['Risk Ranking']=='Medium']

In [38]:
from sklearn.utils import resample

print("Shape of High Risk : ",x_high.shape)
print("Shape of Medium Risk : ",x_medium.shape)
print("Shape of Low Risk : ",x_low.shape)

Shape of High Risk :  (1084, 19)
Shape of Medium Risk :  (7660, 19)
Shape of Low Risk :  (62488, 19)

In [39]:
x_high_unsampled=resample(x_high, replace=True,n_samples=40000,random_state=42)
x_low_unsampled=resample(x_low, replace=False,n_samples=50000,random_state=42)
x_medium_unsampled=resample(x_medium,replace=True,n_samples=40000,random_state=42)
x_low_unsampled.head()

,Nationality,Occupation,Sector,Sender Currency,Sender Amount,PaymentMethod,Sourceof Fund,Purpose,Pickup Country,Relationship,Pickup Type,Risk Ranking,WeekFrequency,MonthFrequency,YearFrequency,Freq2017,Freq2018,Freq2019,Collar_Type
36788,ID,BUILDING_CONSTRUCTION_LABOURERS,Construction,MYR,1888.30,CASH,SALARY,WorkersRemittances,ID,SELF,BANK,Low,2.0,4.0,4.0,2.0,0.0,0.0,blue
47211,ID,EMPLOYMENT_AGENTS_AND_CONTRACTORS,Trading,MYR,288.34,CASH,BUSINESS_INCOME,WorkersRemittances,ID,RELATIVES,BANK,Low,2.0,3.0,46.0,0.0,39.0,0.0,white
34552,MY,CLERICAL_SUPPORT_WORKERS_NOT_ELSEWHERE_CLASSIFIED,Services,MYR,1000.00,CASH,SALARY,WorkersRemittances,ID,FRIENDS,BANK,Low,1.0,2.0,6.0,0.0,5.0,0.0,white
10103,ID,BUILDING_CONSTRUCTION_LABOURERS,Construction,MYR,988.35,CASH,BUSINESS_INCOME,WorkersRemittances,ID,SPOUSE,BANK,Low,4.0,4.0,29.0,0.0,25.0,0.0,blue
32238,NP,CLERICAL_SUPPORT_WORKERS_NOT_ELSEWHERE_CLASSIFIED,Services,MYR,1487.30,CASH,SALARY,WorkersRemittances,NP,PARENTS,CASH,Low,1.0,1.0,8.0,5.0,0.0,0.0,white

In [40]:
x_sampled=pd.concat([x_medium,x_high_unsampled,x_low_unsampled])
x_sampled['Risk Ranking'].value_counts()

X=shuffle(x_sampled)
Z = X.drop(['Risk Ranking'], axis = 1)

In [41]:
y = X['Risk Ranking']
x = X.drop(['Risk Ranking'], axis = 1)
x = pd.get_dummies(x)
x.head()

,Sender Amount,WeekFrequency,MonthFrequency,YearFrequency,Freq2017,Freq2018,Freq2019,Nationality_AU,Nationality_BD,Nationality_DE,...,Relationship_SELF,Relationship_SIBLINGS,Relationship_SPOUSE,Pickup Type_BANK,Pickup Type_BKASH,Pickup Type_CASH,Pickup Type_HOMEDELIVERY,Collar_Type_blue,Collar_Type_no_collar,Collar_Type_white
60388,650.00,3.0,9.0,188.0,0.0,0.0,171.0,0,0,0,...,0,0,0,0,0,1,0,0,0,1
53673,158.14,10.0,16.0,204.0,0.0,0.0,163.0,0,0,0,...,0,0,0,0,0,1,0,0,1,0
65342,289.00,2.0,3.0,4.0,0.0,0.0,3.0,0,0,0,...,1,0,0,1,0,0,0,1,0,0
63674,500.00,1.0,1.0,3.0,0.0,1.0,0.0,0,0,0,...,0,0,0,1,0,0,0,1,0,0
62466,1758.49,1.0,1.0,6.0,0.0,0.0,2.0,0,0,0,...,0,0,0,1,0,0,0,1,0,0

In [44]:
import pickle

pickle_filename = "Z.pkl"  

with open(pickle_filename, 'wb') as file:  
    pickle.dump(Z, file)
    
pickle_filename = "x.pkl"  

with open(pickle_filename, 'wb') as file:  
    pickle.dump(x, file)

In [138]:
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.10, random_state = 42)

In [139]:
model = RandomForestClassifier(n_estimators = 1200, max_features = 'sqrt', max_depth = 180)
model.fit(X_train, y_train)

model_predict = model.predict(X_test)

In [179]:
model_cv_score = cross_val_score(model, x, y, cv = 10)

print("=== Confusion Matrix ===")
print(confusion_matrix(y_test, model_predict))
print('\n')
print("=== Classification Report ===")
print(classification_report(y_test, model_predict))
print('\n')
print("=== All AUC Scores ===")
print(model_cv_score)
print('\n')
print("=== Mean AUC Score ===")
print("Mean AUC Score - Random Forest: ", model_cv_score.mean())

=== Confusion Matrix ===
[[3932    0    0]
 [  44 4935   65]
 [   6  129  655]]


=== Classification Report ===
              precision    recall  f1-score   support

        High       0.99      1.00      0.99      3932
         Low       0.97      0.98      0.98      5044
      Medium       0.91      0.83      0.87       790

    accuracy                           0.98      9766
   macro avg       0.96      0.94      0.95      9766
weighted avg       0.97      0.98      0.97      9766



=== All AUC Scores ===
[0.97675609 0.97808724 0.97747287 0.97409379 0.97614172 0.97808724
 0.97767766 0.97552734 0.97624411 0.97460578]


=== Mean AUC Score ===
Mean AUC Score - Random Forest:  0.9764693835756708

In [180]:
feature_list = x.columns

# Get numerical feature importances
importances = list(model.feature_importances_)

# List of tuples with variable and importance
feature_importances = [(feature, round(importance, 2)) for feature, importance in zip(feature_list, importances)]

# Sort the feature importances by most important first
feature_importances = sorted(feature_importances, key = lambda x: x[1], reverse = True)

# Print out the feature and importances 
[print('Variable: {:20} Importance: {}'.format(*pair)) for pair in feature_importances];

Variable: Sender Amount        Importance: 0.12
Variable: YearFrequency        Importance: 0.12
Variable: MonthFrequency       Importance: 0.09
Variable: Freq2018             Importance: 0.08
Variable: WeekFrequency        Importance: 0.07
Variable: Freq2019             Importance: 0.06
Variable: Freq2017             Importance: 0.02
Variable: Nationality_MY       Importance: 0.02
Variable: Relationship_FRIENDS Importance: 0.02
Variable: Nationality_BD       Importance: 0.01
Variable: Nationality_ID       Importance: 0.01
Variable: Nationality_PH       Importance: 0.01
Variable: Occupation_BANK_TELLERS_AND_RELATED_CLERKS Importance: 0.01
Variable: Occupation_BUILDING_CONSTRUCTION_LABOURERS Importance: 0.01
Variable: Occupation_CLERICAL_SUPPORT_WORKERS_NOT_ELSEWHERE_CLASSIFIED Importance: 0.01
Variable: Occupation_EMPLOYMENT_AGENTS_AND_CONTRACTORS Importance: 0.01
Variable: Occupation_MANUFACTURING_LABOURERS_NOT_ELSEWHERE_CLASSIFIED Importance: 0.01
Variable: Sector_BankingAndFinancial Importance: 0.01
Variable: Sector_Construction  Importance: 0.01
Variable: Sector_Manufacturing Importance: 0.01
Variable: Sector_Others        Importance: 0.01
Variable: Sector_Plantation    Importance: 0.01
Variable: Sector_Services      Importance: 0.01
Variable: PaymentMethod_CASH   Importance: 0.01
Variable: PaymentMethod_ONLINE Importance: 0.01
Variable: Sourceof Fund_FRIENDS Importance: 0.01
Variable: Sourceof Fund_SALARY Importance: 0.01
Variable: Sourceof Fund_SAVINGS Importance: 0.01
Variable: Purpose_GoodsandServices Importance: 0.01
Variable: Purpose_GrantsandGifts Importance: 0.01
Variable: Purpose_WorkersRemittances Importance: 0.01
Variable: Pickup Country_ID    Importance: 0.01
Variable: Pickup Country_PH    Importance: 0.01
Variable: Relationship_CHILDREN Importance: 0.01
Variable: Relationship_PARENTS Importance: 0.01
Variable: Relationship_RELATIVES Importance: 0.01
Variable: Relationship_SELF    Importance: 0.01
Variable: Relationship_SIBLINGS Importance: 0.01
Variable: Relationship_SPOUSE  Importance: 0.01
Variable: Pickup Type_BANK     Importance: 0.01
Variable: Pickup Type_CASH     Importance: 0.01
Variable: Collar_Type_blue     Importance: 0.01
Variable: Collar_Type_white    Importance: 0.01
Variable: Nationality_AU       Importance: 0.0
Variable: Nationality_DE       Importance: 0.0
Variable: Nationality_EG       Importance: 0.0
Variable: Nationality_IN       Importance: 0.0
Variable: Nationality_IT       Importance: 0.0
Variable: Nationality_JP       Importance: 0.0
Variable: Nationality_KH       Importance: 0.0
Variable: Nationality_KR       Importance: 0.0
Variable: Nationality_LK       Importance: 0.0
Variable: Nationality_MM       Importance: 0.0
Variable: Nationality_MV       Importance: 0.0
Variable: Nationality_NP       Importance: 0.0
Variable: Nationality_PK       Importance: 0.0
Variable: Nationality_SG       Importance: 0.0
Variable: Nationality_TH       Importance: 0.0
Variable: Nationality_TR       Importance: 0.0
Variable: Nationality_VN       Importance: 0.0
Variable: Occupation_ACCOUNTING_ASSOCIATE_PROFESSIONALS Importance: 0.0
Variable: Occupation_ADMINISTRATIVE_AND_EXECUTIVE_SECRETARIES Importance: 0.0
Variable: Occupation_ADMINISTRATIVE_MANAGERS Importance: 0.0
Variable: Occupation_ADMINISTRATIVE_PROFESSIONALS Importance: 0.0
Variable: Occupation_ADVERTISING_AND_MARKETING_PROFESSIONALS Importance: 0.0
Variable: Occupation_AGRICULTURAL_FORESTRY_FARMING_AND_FISHERY_WORKERS_NOT_ELSEWHERE_CLASSIFIED Importance: 0.0
Variable: Occupation_ARTS_TEACHERS Importance: 0.0
Variable: Occupation_Accountants Importance: 0.0
Variable: Occupation_BARTENDERS Importance: 0.0
Variable: Occupation_BUSINESS_SERVICES_MANAGERS Importance: 0.0
Variable: Occupation_CAR_TAXI_AND_VAN_DRIVERS Importance: 0.0
Variable: Occupation_CASHIERS_AND_TICKET_CLERKS Importance: 0.0
Variable: Occupation_CHEFS     Importance: 0.0
Variable: Occupation_CHEMICAL_PRODUCTS_PLANT_AND_MACHINE_OPERATORS Importance: 0.0
Variable: Occupation_CHILD_CARE_WORKERS Importance: 0.0
Variable: Occupation_CIVIL_ENGINEERING_LABOURERS Importance: 0.0
Variable: Occupation_CLEANERS_AND_HELPERS_IN_OFFICES_HOTEL_AND_OTHER_ESTABLISHMENTS Importance: 0.0
Variable: Occupation_CLIENT_INFORMATION_WORKERS_NOT_ELSEWHERE_CLASSIFIED Importance: 0.0
Variable: Occupation_CODING_PROOF_READING_AND_RELATED_CLERKS Importance: 0.0
Variable: Occupation_CONSTRUCTION_MANAGERS Importance: 0.0
Variable: Occupation_CONSTRUCTION_SUPERVISORS Importance: 0.0
Variable: Occupation_COOKS     Importance: 0.0
Variable: Occupation_CROP_FARM_LABOURERS Importance: 0.0
Variable: Occupation_CUSTOMER_SERVICE_or_CONTACT_or_CALL_CENTRE_INFORMATION_CLERKS Importance: 0.0
Variable: Occupation_DATA_ENTRY_CLERKS Importance: 0.0
Variable: Occupation_DESPATCH_or_RUNNER Importance: 0.0
Variable: Occupation_DOMESTIC_CLEANERS_AND_HELPERS Importance: 0.0
Variable: Occupation_DOMESTIC_HOUSEKEEPERS Importance: 0.0
Variable: Occupation_ELECTRONICS_ENGINEERING_TECHNICIANS Importance: 0.0
Variable: Occupation_ENGINEERING_PROFESSIONALS_NOT_ELSEWHERE_CLASSIFIED Importance: 0.0
Variable: Occupation_FIELD_CROP_GROWERS Importance: 0.0
Variable: Occupation_FINANCE_MANAGERS_OTHERS Importance: 0.0
Variable: Occupation_FINANCE_MANAGERS_SERVICES Importance: 0.0
Variable: Occupation_FINANCIAL_ANALYSTS Importance: 0.0
Variable: Occupation_FINANCIAL_AND_INVESTMENT_ADVISERS Importance: 0.0
Variable: Occupation_FOOD_COUNTER_ATTENDANTS Importance: 0.0
Variable: Occupation_GENERALIST_MEDICAL_PRACTITIONERS Importance: 0.0
Variable: Occupation_GENERAL_DUTY_OFFICERS_(MA) Importance: 0.0
Variable: Occupation_HAND_OR_PEDAL_VEHICLE_DRIVERS Importance: 0.0
Variable: Occupation_HEAVY_TRUCK_AND_LORRY_DRIVERS Importance: 0.0
Variable: Occupation_HouseWife Importance: 0.0
Variable: Occupation_INDUSTRIAL_AND_PRODUCTION_ENGINEERS Importance: 0.0
Variable: Occupation_INFORMATION_AND_COMMUNICATIONS_TECHNOLOGY_MANAGERS Importance: 0.0
Variable: Occupation_KITCHEN_HELPERS Importance: 0.0
Variable: Occupation_LEGAL_PROFESSIONALS_NOT_ELSEWHERE_CLASSIFIED Importance: 0.0
Variable: Occupation_MANAGING_DIRECTORS_AND_CHIEF_EXECUTIVES_AGRICULTURE Importance: 0.0
Variable: Occupation_MANAGING_DIRECTORS_AND_CHIEF_EXECUTIVES_CONSTRUCTION Importance: 0.0
Variable: Occupation_MANAGING_DIRECTORS_AND_CHIEF_EXECUTIVES_MANUFACTURING Importance: 0.0
Variable: Occupation_MANAGING_DIRECTORS_AND_CHIEF_EXECUTIVES_OTHERS Importance: 0.0
Variable: Occupation_MANAGING_DIRECTORS_AND_CHIEF_EXECUTIVES_SERVICES Importance: 0.0
Variable: Occupation_MANUFACTURING_MANAGERS Importance: 0.0
Variable: Occupation_MANUFACTURING_SUPERVISORS Importance: 0.0
Variable: Occupation_MECHANICAL_ENGINEERS Importance: 0.0
Variable: Occupation_MEDICAL_ASSISTANTS Importance: 0.0
Variable: Occupation_MINING_SUPERVISORS Importance: 0.0
Variable: Occupation_MOTORCYCLE_RIDERS_(DRIVERS) Importance: 0.0
Variable: Occupation_MOTOR_VEHICLE_TECHNICIANS Importance: 0.0
Variable: Occupation_OTHER_SERVICES_MANAGERS_NOT_ELSEWHERE_CLASSIFIED Importance: 0.0
Variable: Occupation_OTHER_SUPERVISORS_NOT_ELSEWHERE_CLASSIFIED Importance: 0.0
Variable: Occupation_PRODUCTION_CLERKS Importance: 0.0
Variable: Occupation_RELIGIOUS_TEACHERS Importance: 0.0
Variable: Occupation_RETAIL_AND_WHOLESALE_TRADE_MANAGERS Importance: 0.0
Variable: Occupation_RETIREE   Importance: 0.0
Variable: Occupation_SALES_AND_MARKETING_MANAGERS Importance: 0.0
Variable: Occupation_SALES_DEMONSTRATORS Importance: 0.0
Variable: Occupation_SALES_WORKERS_NOT_ELSEWHERE_CLASSIFIED Importance: 0.0
Variable: Occupation_SECONDARY_EDUCATION_TEACHERS Importance: 0.0
Variable: Occupation_SECURITY_GUARDS Importance: 0.0
Variable: Occupation_SHIP_ENGINEERS Importance: 0.0
Variable: Occupation_SHOPKEEPERS Importance: 0.0
Variable: Occupation_SHOP_SALES_ASSISTANTS Importance: 0.0
Variable: Occupation_SHOP_SUPERVISORS Importance: 0.0
Variable: Occupation_STALL_AND_MARKET_SALESPERSONS Importance: 0.0
Variable: Occupation_STUDENT   Importance: 0.0
Variable: Occupation_SYSTEMS_ANALYSTS Importance: 0.0
Variable: Occupation_TEACHERâ€™S_AIDES Importance: 0.0
Variable: Occupation_TEACHING_PROFESSIONALS_NOT_ELSEWHERE_CLASSIFIED Importance: 0.0
Variable: Occupation_TOURISTS  Importance: 0.0
Variable: Occupation_TRAINING_AND_STAFF_DEVELOPMENT_PROFESSIONALS Importance: 0.0
Variable: Occupation_TRANSPORT_CONDUCTORS Importance: 0.0
Variable: Occupation_TRAVEL_GUIDES_or_AGENTS Importance: 0.0
Variable: Occupation_UNIVERSITY_AND_HIGHER_EDUCATION_TEACHING_PROFESSIONAL Importance: 0.0
Variable: Occupation_UNKNOWN   Importance: 0.0
Variable: Occupation_Unemployed Importance: 0.0
Variable: Sector_Agriculture   Importance: 0.0
Variable: Sector_Association   Importance: 0.0
Variable: Sector_Chemical      Importance: 0.0
Variable: Sector_ComputerTechnology Importance: 0.0
Variable: Sector_Education     Importance: 0.0
Variable: Sector_Energy        Importance: 0.0
Variable: Sector_Engineering   Importance: 0.0
Variable: Sector_Entertainment Importance: 0.0
Variable: Sector_FoodAndBeverage Importance: 0.0
Variable: Sector_Government    Importance: 0.0
Variable: Sector_NonProfitOrganization Importance: 0.0
Variable: Sector_Professional  Importance: 0.0
Variable: Sector_Restaurant    Importance: 0.0
Variable: Sector_Trading       Importance: 0.0
Variable: Sender Currency_MYR  Importance: 0.0
Variable: PaymentMethod_DEBITCARD Importance: 0.0
Variable: PaymentMethod_NONE   Importance: 0.0
Variable: PaymentMethod_ONLINE.DEBITCARD Importance: 0.0
Variable: PaymentMethod_VIRTUALACCOUNT Importance: 0.0
Variable: Sourceof Fund_BUSINESS_INCOME Importance: 0.0
Variable: Sourceof Fund_CasinoWinning Importance: 0.0
Variable: Sourceof Fund_DONATIONS Importance: 0.0
Variable: Sourceof Fund_FAMILY_INCOME Importance: 0.0
Variable: Sourceof Fund_LOAN   Importance: 0.0
Variable: Sourceof Fund_LOTTERY Importance: 0.0
Variable: Sourceof Fund_MONTHLY_INCOME Importance: 0.0
Variable: Sourceof Fund_OTHERS Importance: 0.0
Variable: Sourceof Fund_RELATIVES Importance: 0.0
Variable: Purpose_BeveragesandTobacco Importance: 0.0
Variable: Purpose_ComputerServices Importance: 0.0
Variable: Purpose_ConstructionandInstallationServicesAbroad Importance: 0.0
Variable: Purpose_CurrentTransfersGovernmentSector Importance: 0.0
Variable: Purpose_DepositswithfromFinancialInstitutionsinMalaysia Importance: 0.0
Variable: Purpose_EducationRelated Importance: 0.0
Variable: Purpose_EducationServices Importance: 0.0
Variable: Purpose_EmployersSocialContributions Importance: 0.0
Variable: Purpose_FinancialLease Importance: 0.0
Variable: Purpose_FinesandPenaltiesPrivateSector Importance: 0.0
Variable: Purpose_FoodandLiveAnimals Importance: 0.0
Variable: Purpose_GoodsandServicesbyTravellers Importance: 0.0
Variable: Purpose_GovernmentSecurities Importance: 0.0
Variable: Purpose_HealthRelated Importance: 0.0
Variable: Purpose_HealthServices Importance: 0.0
Variable: Purpose_InformationServices Importance: 0.0
Variable: Purpose_Interest     Importance: 0.0
Variable: Purpose_InvestmentFundShares Importance: 0.0
Variable: Purpose_InvestmentIncome Importance: 0.0
Variable: Purpose_LicenseFeestoReproduceandDistributeIntellectualProperty Importance: 0.0
Variable: Purpose_ManagementConsultingServices Importance: 0.0
Variable: Purpose_ManufacturedGoods Importance: 0.0
Variable: Purpose_MerchantingTrade Importance: 0.0
Variable: Purpose_MiscellaneousManufacturedArticles Importance: 0.0
Variable: Purpose_MiscellaneousTransactionsandCommoditiesnce Importance: 0.0
Variable: Purpose_OTHERS       Importance: 0.0
Variable: Purpose_OtherBusinessServicesNotClassifiedElsewhere Importance: 0.0
Variable: Purpose_OtherCurrentTransfersNotClassifiedElsewherePrivateSector Importance: 0.0
Variable: Purpose_OtherLoanFacilitiesShortTerm Importance: 0.0
Variable: Purpose_OtherPersonalServices Importance: 0.0
Variable: Purpose_OtherSupportingandAuxiliaryTransportServices Importance: 0.0
Variable: Purpose_PassengerFare Importance: 0.0
Variable: Purpose_PilgrimageReligiousRelated Importance: 0.0
Variable: Purpose_RealEstateAbroad Importance: 0.0
Variable: Purpose_RealEstateinHostCountry Importance: 0.0
Variable: Purpose_ReimbursementformInternationalOrganisations Importance: 0.0
Variable: Purpose_RentalonNaturalResources Importance: 0.0
Variable: Purpose_SocialBenefitsPrivateSector Importance: 0.0
Variable: Purpose_SuppliersCreditShortTerm Importance: 0.0
Variable: Purpose_TaxesonIncomeWealthandOtherTaxableAssetsPrivateSector Importance: 0.0
Variable: Purpose_TermLoansLongTerm Importance: 0.0
Variable: Purpose_TermLoansShortTerm Importance: 0.0
Variable: Purpose_TradeRelatedServices Importance: 0.0
Variable: Purpose_WagesandSalariesinCash Importance: 0.0
Variable: Purpose_WagesandSalariesinKindBenefitsAttributabletoEmployees Importance: 0.0
Variable: Pickup Country_AU    Importance: 0.0
Variable: Pickup Country_BD    Importance: 0.0
Variable: Pickup Country_CN    Importance: 0.0
Variable: Pickup Country_IN    Importance: 0.0
Variable: Pickup Country_KH    Importance: 0.0
Variable: Pickup Country_LK    Importance: 0.0
Variable: Pickup Country_MY    Importance: 0.0
Variable: Pickup Country_NP    Importance: 0.0
Variable: Pickup Country_PK    Importance: 0.0
Variable: Pickup Country_SG    Importance: 0.0
Variable: Pickup Country_TH    Importance: 0.0
Variable: Pickup Country_VN    Importance: 0.0
Variable: Relationship_BUSINESS_ASSOCIATES Importance: 0.0
Variable: Relationship_CREDITOR Importance: 0.0
Variable: Relationship_EMPLOYEE Importance: 0.0
Variable: Pickup Type_BKASH    Importance: 0.0
Variable: Pickup Type_HOMEDELIVERY Importance: 0.0
Variable: Collar_Type_NaN      Importance: 0.0
Variable: Collar_Type_no_collar Importance: 0.0

In [ ]:
"""""""""
# number of trees in random forest
n_estimators = [int(x) for x in np.linspace(start = 200, stop = 2000, num = 10)]

# number of features at every split
max_features = ['auto', 'sqrt']

# max depth
max_depth = [int(x) for x in np.linspace(100, 500, num = 11)]
max_depth.append(None)

# create random grid
random_grid = {
     'n_estimators': n_estimators,
     'max_features': max_features,
     'max_depth': max_depth
 }
# Random search of parameters
model_random = RandomizedSearchCV(estimator = model, param_distributions = random_grid, n_iter = 100, cv = 3, verbose=2, random_state=42, n_jobs = -1)

# Fit the model
model_random.fit(X_train, y_train)

# print results
print(model_random.best_params_)
"""

In [ ]:
""""
model = RandomForestClassifier(n_estimators = 1200, max_features = 'sqrt', max_depth = 180)
model.fit(X_train, y_train)

model_predict = model.predict(X_test)

model_cv_score = cross_val_score(model, x, y, cv = 10)

print("=== Confusion Matrix ===")
print(confusion_matrix(y_test, model_predict))
print('\n')
print("=== Classification Report ===")
print(classification_report(y_test, model_predict))
print('\n')
print("=== All AUC Scores ===")
print(model_cv_score)
print('\n')
print("=== Mean AUC Score ===")
print("Mean AUC Score - Random Forest: ", model_cv_score.mean())
"""

In [143]:
pickle_filename = "MODEL.pkl"  

with open(pickle_filename, 'wb') as file:  
    pickle.dump(model, file)